linker: linker.cpp Header.h Readers.h
	g++ -g linker.cpp -o linker
	# g++ -Wall -pedantic -g -c -o linker.o linker.cpp Readers.h Header.h
	# g++ -Wall -pedantic -g linker.o -o exec

clean:
	rm -f linker *~